FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y python3.11 python3.11-dev python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.gpu.txt .
RUN pip3 install --no-cache-dir -r requirements.gpu.txt

COPY main.py .

EXPOSE 8002

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
